### ISSUE TITLE
路由策略权重只在第一次请求生效，之后更新策略后无法生效

### ISSUE THREAD

**Issue by GitMoons** [go-chassis/sc-client#15]
github.com/ServiceComb/go-chassis/core/router/router.go:87

// FitRate fit rate
func FitRate(tags []*model.RouteTag, dest string) *model.RouteTag {
	if tags[0].Weight == 100 {
		return tags[0]
	}

	pool, ok := wp.GetPool().Get(dest)
	if !ok {
		// first request route to tags[0]
		wp.GetPool().Set(dest, wp.NewPool(tags...))
		return tags[0]
	}
	return pool.PickOne()
}
以上逻辑会在第一次请求初始化权重池，初始化之后一直缓存，之后更新策略也不会重置，导致更新后权重策略无法生效

**Comment by GitMoons** [comment]
更新策略后可以通过weightpool.GetPool().Reset重置，但存在多个策略时，只会生效第一次匹配到的策略权重，之后就算匹配到其他策略也会按第一次匹配到的策略中的权重分配

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/pull/933 已解决
