### ISSUE TITLE
鉴权模块问题

### ISSUE THREAD

**Issue by bodhisatan** [go-chassis/sc-client#54]
https://github.com/go-chassis/sc-client/blob/master/client_test.go#L263
TestClient_Auth单测会因为这一行的if语句直接退出，走不到下面的逻辑
我注释掉之后，会在调用GetToken方法的时候报一个404的错误码

**Comment by OnePaiGu** [comment]
这个是因为需要service-center开启rbac模块之后才能测试下面的功能，不能直接删除，开启方式参考：https://service-center.readthedocs.io/en/latest/user-guides/rbac.html
